### ISSUE TITLE
exiftag.rb:38:in `render': undefined method

### ISSUE THREAD

**Issue by vitto** [benib/jekyll-exiftag#1]
Hi, I'm trying to test a tag like in the tutorial, I've moved the plugin on `_plugins` directory but when i build the site I've got this error:

```
/_plugins/exiftag.rb:38:in `render': undefined method `[]' for nil:NilClass (NoMethodError)
```

I've used the tag as in the tutorial:

```
{% exiftag model /path/to/ image.jpg %}
```

I hope I've wrote the code right but I'm not sure.

I've installed `exifr` as needed by the plugin but it doesn't seems to work.
I'm using Yosemite, so it's on Ruby 2.0, I hope it helps.

**Comment by vitto** [comment]
Sorry, it was my mistake, it seems I must set on _config.yml the path, so it seems to be useless the path set on the tag?

This with config works:

```
{% exiftag model, nil, pollo-cambogia.jpg %}
```

This without config not working:

```
{% exiftag model, img/posts/photos, pollo-cambogia.jpg %}
```

**Comment by benib** [comment]
Thanks for the report. I'll have a look at this in the next days.

From a first glance I think if the bug is that you have to set `sources` in the config to make the plugin work. If you do that, it should be possible to add an additional source as the 2nd parameter to the tag.

**Comment by benib** [comment]
@vitto can you confirm that this is fixed with version `0.0.3` of jekyll-exiftag? You can also just get the current master if you haven't installed with `gem install`.

**Comment by benib** [comment]
@vitto I'd be very glad if you could take the time to test this and get back with results. It worked for my tests, but it would be nice to be sure that your issue is resolved.

**Comment by vitto** [comment]
hey @benib, thanks, I'll check it out this week-end and I'll give you feedback.

**Comment by benib** [comment]
@vitto any news? Otherwise I'm just going to close this issue as it is fixed as far as my test tells.

**Comment by ghost** [comment]
Hey @benib,

I'm having a similar issue:

```
Liquid Exception: undefined method `[]' for nil:NilClass in _includes/photos.html, included in _layouts/default.html
```

The file `_includes/photos.html` contains the following line:

```
{% exiftag model, path/to/my_photos, photo.jpg %}
```

The error goes away if I put this is in my `_config.yml`:

``` yaml
exiftag:
  sources:
    - path/to/my_photos
```

I'm using the very latest version in my `_plugins` directory, taken from here:

https://github.com/benib/jekyll-exiftag/blob/6207ae2c40e9560c86f10ce1280e40505e0c106a/lib/jekyll-exiftag.rb

Any help would be hugely appreciated!

**Comment by benib** [comment]
@ribmo Thank you for the report. This is fixed with v.0.0.4.

You shouldn't get this error anymore when not having a `exiftag` config in your `config.yml`.

I just pushed the release to rubygems.org. Install it from there or get `jekyll_exiftag.rb` from here: https://github.com/benib/jekyll-exiftag/blob/0.0.4/lib/jekyll-exiftag.rb

Can you confirm that it's working for you?

**Comment by benib** [comment]
@ribmo v0.0.4 had another issue. Please use v0.0.5.
https://github.com/benib/jekyll-exiftag/blob/0.0.5/lib/jekyll-exiftag.rb

**Comment by benib** [comment]
@ribmo Does version 0.0.5 work for you?

**Comment by ghost** [comment]
@benib Yes, 0.0.5 works for me. Thank you!
