### ISSUE TITLE
Documentation could do with an example of usage

### ISSUE THREAD

**Issue by FraserThompson** [benib/jekyll-exiftag#5]
Particularly the liquid tag usage as it's not super clear what the 'file' variable is supposed to look like.

**Comment by benib** [comment]
@FraserThompson thanks for pointing it out. Would you like to send a pull request adding some information to README.md?

**Comment by FraserThompson** [comment]
The reason why I think there's a need for an example is because I couldn't get it working the way I expected. So I don't think I'm qualified enough to write documentation unfortunately.

**Comment by benib** [comment]
I update the README trying to make it more clear, what ```file``` should look like.
